logging:
  level:
    org.springframework: error
    com.overlook.core: debug

spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .html

server:
  servlet:
    context-path: /overlook
