logging:
  level:
    org.springframework: error
    com.overlook.core: debug

spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /overlook

overlook:
  security:
    jwtSecret: 2eA!#]+2l3#$5-
    jwtExpiration: 3600000
